### ISSUE TITLE
Build problem.

### ISSUE THREAD

**Issue by OmidID** [gleblebedev/Urho3DMaterialGraphEditor#1]
![image](https://user-images.githubusercontent.com/956077/43367284-3c6070d6-9353-11e8-90d1-0ba1b71d97bd.png)
I have this problem. I think because of .Net Standard it is. 
Should I add it to the packages?

**Comment by gleblebedev** [comment]
Yes, please :-)

**Comment by OmidID** [comment]
It's worse  !
Object is not defined :D 
![image](https://user-images.githubusercontent.com/956077/43367537-4183762c-9357-11e8-8bff-d1699e7fc791.png)

**Comment by gleblebedev** [comment]
Are you on visual studio 2017? With recent updates installed?

**Comment by OmidID** [comment]
15.7.2 the last one is 15.7.5. i going to upgrade it

**Comment by OmidID** [comment]
Now I have another problem
![image](https://user-images.githubusercontent.com/956077/43368093-4a240a04-9360-11e8-9c21-b41e340c1f0e.png)

**Comment by gleblebedev** [comment]
This one is easy. Just restore nuget packages on solution.

**Comment by OmidID** [comment]
yeh already i did. actually i did that 2 times to be sure.as you see in photo the assembly already added to the references.

**Comment by gleblebedev** [comment]
I've included problematic packages in the repository. Should work now.

**Comment by OmidID** [comment]
👍 it's ok now
